// Generated by CoffeeScript 1.8.0
var ClientsViewModel, root;

ClientsViewModel = (function() {
  function ClientsViewModel() {}

  return ClientsViewModel;

})();

root = typeof exports !== "undefined" && exports !== null ? exports : window;

root.ClientsViewModel = ClientsViewModel;
