// Generated by CoffeeScript 1.8.0
var root, webdis,
  __slice = [].slice;

webdis = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return "http://trust-blitz.codio.io:7379/" + args.join('/');
};

root = typeof exports !== "undefined" && exports !== null ? exports : window;

root.webdis = webdis;
