// Generated by CoffeeScript 1.8.0
var $, config, getAll, root;

$ = jQuery;

config = require('./config');

getAll = function(collection) {
  var keys_url;
  keys_url = config.webdis("KEYS", collection);
  return $.ajax(keys_url, {
    type: 'GET',
    dataType: 'json',
    success: function(data, textStatus, jqXHR) {
      return console.log("Successful AJAX call: " + data);
    }
  });
};

root = typeof exports !== "undefined" && exports !== null ? exports : window;

root.getAll = getAll;
